return {
	"nvim-treesitter/nvim-treesitter",
	version = vim.fn.has("nvim-0.12") == 1 and "v0.9.2" or "v0.9.3",
	lazy = false,
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter.configs").setup({
			ensure_installed = {
				"lua",
				"vim",
				"vimdoc",
				"python",
				"javascript",
				"typescript",
				"html",
				"css",
				"json",
				"yaml",
				"toml",
				"c",
				"cpp",
				"rust",
				"go",
				"java",
				"kotlin",
				"bash",
				"fish",
				"markdown",
				"markdown_inline",
				"sql",
				"graphql",
				"dockerfile",
				"terraform",
				"regex",
				"comment",
			},
			highlight = { enable = true },
			indent = { enable = true },
		})
	end,
}
